REM ============================================
REM ASSIGNESP.SP
REM DATE: 2014-05-07
REM ============================================

SELECT DISK %HPRM.ESP.DISKINDEX%
LIST PART
LIST VOL
SELECT PARTITION %HPRM.ESP.PARTINDEX%
ASSIGN LETTER=%CRM.ESP.DRVLETTER%
LIST PART
LIST VOL
EXIT