REM ============================================
REM ASSIGNWINRE.SP
REM DATE: 2014-05-07
REM ============================================

SELECT DISK %HPRM.WINRE.DISKINDEX%
LIST PART
LIST VOL
SELECT PARTITION %HPRM.WINRE.PARTINDEX%
ASSIGN LETTER=%CRM.WINRE.DRVLETTER%
LIST PART
LIST VOL
EXIT